app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

//Ruta de inicio

	Route::get('/', ['as' => '/', function () {
    return view('auth.login');
	}]);


//Grupo de rutas para el administrador

	Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'admin']], function(){

		Route::get('/', ['as' => 'inicio', function () {
	    	return redirect()->route('admin.users.index');
		}]);

//Rutas para el modulo de usuarios en el panel del administrador

	Route::resource('users', 'UsersController');

	Route::get('users/{id}/destroy', [

		'uses' => 'UsersController@destroy',
		'as' => 'admin.users.destroy'

	]);

	Route::get('users/{id}/detalles', [

		'uses' => 'UsersController@detalles',
		'as' => 'admin.users.detalles'

	]);

//Rutas para el modulo de tareas en el panel del administrador

	Route::resource('tareas', 'TareasController');

	Route::get('misasignaciones', [

		'uses' 	=> 'TareasController@asignacionesAdmin',
		'as'	=> 'admin.tareas.asignaciones'

		]);

	Route::get('tareas/{id}/destroy', [

		'uses' => 'TareasController@destroy',
		'as' => 'admin.tareas.destroy'

	]);

	Route::get('tareas/{id}/detalles', [

		'uses' => 'TareasController@detalles',
		'as' => 'admin.tareas.detalles'

	]);

	Route::get('tareas/{id}/asignar/',[

		'uses' 	=> 'TareasController@asignar',
		'as' 	=> 'admin.tareas.asignar'

	]);

	Route::get('tareas/{id}/generaPDF',[

		'uses' 	=> 'TareasController@generaPDF',
		'as' 	=> 'admin.tareas.generaPDF'

	]);

	Route::post('tareas/{id}/saveasign',[

		'uses' 	=> 'TareasController@saveasign',
		'as' 	=> 'admin.tareas.saveasign'

	]);

//Rutas para el modulo de reportes en el panel del administrador

	Route::resource('reportes', 'ReportController');

	Route::get('estadisticas',[

			'uses' => 'ReportController@muestaEstadistica',
			'as' => 'admin.reports.stadistics'

		]);

	Route::get('generador',[

		'uses' => 'ReportController@generator',
		'as' => 'admin.reports.generator'

		]);

	Route::post('reportes',[

		'uses' => 'ReportController@generaReport',
		'as' => 'admin.reports.genera'

		]);


//Aqui terminan las rutas el modulo de reportes.

}); //aqui termina el grupo de rutas para el admin

//Aqui comienza el grupo de rutas para los empleados

	Route::group(['prefix' => 'members', 'middleware' => 'auth'], function(){

		Route::get('/', ['as' => 'inicio', function () {
	    	return redirect()->route('members.tareas.index');
		}]);

		Route::resource('tareas', 'MembersController');

			Route::get('tareas/{id}/detalles', [

			'uses' => 'TareasController@detallesMembers',
			'as' => 'members.tareas.detalles'

		]);

		Route::get('tareas/{id}/destroy', [

			'uses' => 'TareasController@destroy',
			'as' => 'members.tareas.destroy'

		]);

		Route::get('tareas/{id}/generaPDF',[

			'uses' 	=> 'TareasController@generaPDF',
			'as' 	=> 'members.tareas.generaPDF'

		]);

		Route::get('tareas/{id}/editmembers',[

			'uses' 	=> 'TareasController@editmembers',
			'as' 	=> 'members.tareas.editmembers'

		]);

		Route::put('tareas/{id}/updatemembers',[

			'uses' 	=> 'TareasController@updatemembers',
			'as' 	=> 'members.tareas.updatemembers'

		]);

	//Rutas para el modulo de reportes en el panel de usuarios

	Route::get('index',[

			'uses' => 'ReportController@reportsIndexMembers',
			'as' => 'members.reports.index'

		]);

	Route::get('estadisticas',[

			'uses' => 'ReportController@muestaEstadistica',
			'as' => 'members.reports.stadistics'

		]);

	Route::get('generador',[

		'uses' => 'ReportController@membersgenerator',
		'as' => 'members.reports.membersgenerator'

		]);

	Route::post('reportes',[

		'uses' => 'ReportController@membersgeneraReport',
		'as' => 'empleado.reports.genera'

		]);

	});


//Rutas para la autenticacion de usuarios (login)

Route::get('auth/login', [

	'uses'	=> 	'Auth\AuthController@getLogin',
	'as'	=>	'auth.login'

	]);

Route::post('auth/login', [

	'uses'	=> 	'Auth\AuthController@postLogin',
	'as'	=>	'auth.login'

	]);

Route::get('admin/auth/logout', [

	'uses'	=> 	'Auth\AuthController@getLogout',
	'as'	=>	'auth.logout'

	]); //aqui terminan las rutas para la autenticacion de usuarios

app/Tarea.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;


class Tarea extends Model
{
    protected $table = 'tarea';

    protected $fillable = ['status_tarea', 'prioridad_tarea', 'nombre_tarea', 'descripcion_tarea', 'fecha_inicio', 'fecha_limite', 'fecha_fin'];
    
    public function empleado_tarea(){

    	return $this->belongsTo('App\Empleado_tarea');

    }

    public function scopeSearchTarea($query, $name){

        return $query->where('nombre_tarea', 'LIKE', "%$name%");

    }
}

app/Http/Controllers/TareasController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Tarea;
use App\Http\Requests;
use Laracasts\Flash\Flash;
use App\Http\Controllers\Controller;
use App\Http\Requests\TareaRegistroRequest;
use App\User;
use App\Empleado_tarea;
use Carbon\Carbon;

class TareasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $tareas = Tarea::searchtarea($request->name)->orderBy('prioridad_tarea', 'ASC')->paginate(7);
        return view('admin.tareas.index')->with('tareas', $tareas);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.tareas.create_tarea');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(TareaRegistroRequest $request)
    {
        $tarea = new Tarea($request->all());
        $tarea->save();
        
        //enviamos un mensaje con flash de exito antes de redireccionar.
        Flash::success('La tarea ' . $tarea->nombre_tarea . " ha sido creada exitosamente.");

        //indicamos a que ruta queremos ser redireccionados despues de guardar al usuario
        return redirect()->route('admin.tareas.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    
    public function edit($id)
    {
        $tarea = Tarea::find($id);

        $fecha_i = date_create($tarea->fecha_inicio);
        $tarea->fecha_inicio = date_format($fecha_i, 'd-m-Y');
        $fecha_l = date_create($tarea->fecha_limite);
        $tarea->fecha_limite = date_format($fecha_l, 'd-m-Y');
        return view('admin.tareas.edit')->with('tarea', $tarea);
    }

    public function generaPDF($id)
    {
        $tarea = Tarea::find($id);

        $fecha_i = date_create($tarea->fecha_inicio);
        $tarea->fecha_inicio = date_format($fecha_i, 'd-m-Y');
        $fecha_l = date_create($tarea->fecha_limite);
        $tarea->fecha_limite = date_format($fecha_l, 'd-m-Y');
        $fecha_f = date_create($tarea->fecha_fin);
        $tarea->fecha_fin = date_format($fecha_f, 'd-m-Y');
        
        $view =  \View::make('admin.tareas.pdf', compact('tarea'))->render();
        $pdf = \App::make('dompdf.wrapper');
        $pdf->loadHTML($view);
        return $pdf->stream();
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $tarea = Tarea::find($id);
        // $tarea->nombre_tarea = $request->nombre_tarea;
        // $tarea->prioridad_tarea = $request->prioridad_tarea;
        // $tarea->status_tarea = $request->status_tarea;
        // $tarea->descripcion_tarea = $request->descripcion_tarea;
        // $tarea->fecha_inicio = $request->fecha_inicio;
        // $tarea->fecha_fin = $request->fecha_fin;
        $tarea->fill($request->all());
        $tarea->save();

        Flash::warning("La tarea " .$tarea->nombre_tarea. " ha sido actualizada correctamente.");
        return redirect()->route('admin.tareas.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $tarea = Tarea::find($id);
        $tarea->delete();

        Flash::warning("La tarea " .$tarea->nombre_tarea. " ha sido eliminada correctamente.");
        return redirect()->route('admin.tareas.index');
    }

    public function detalles($id)
    {
        $tarea = Tarea::find($id);
        $fecha_i = date_create($tarea->fecha_inicio);
        $tarea->fecha_inicio = date_format($fecha_i, 'd-m-Y');
        $fecha_l = date_create($tarea->fecha_limite);
        $tarea->fecha_limite = date_format($fecha_l, 'd-m-Y');
        $fecha_f = date_create($tarea->fecha_fin);
        $tarea->fecha_fin = date_format($fecha_f, 'd-m-Y');
        return view('admin.tareas.detalles')->with('tarea', $tarea);
    }

    public function asignar($id)
    {
        $tarea = Tarea::find($id);
        $usuarios = User::orderBy('type', 'DESC')->paginate();
        return view('admin.tareas.asignar')->with('tarea', $tarea)->with('usuarios', $usuarios);
    }

    public function saveasign(Request $request, $id) 
    {
        
        foreach ($request->id_usuario as $id_usuario) {
            $relacion = new Empleado_tarea();
            $relacion->id = $id_usuario;
            $relacion->id_tarea = $id;
            $relacion->save();
        }
        

        Flash::warning('La tarea ha sido asignada correctamente.');
        return redirect()->route('admin.tareas.index');

    }

    public function asignacionesAdmin()
    {

        $tareas = \DB::table('empleado_tarea')  ->select('empleado_tarea.*',

                                                        'empleado_tarea.id as id_empleado',
                                                        'tarea.id as id_tarea',
                                                        'tarea.nombre_tarea',
                                                        'tarea.prioridad_tarea',
                                                        'tarea.status_tarea'

                                                        )
                                                ->join('tarea', 'tarea.id', '=', 'empleado_tarea.id')
                                                ->join('users', 'users.id', '=', 'empleado_tarea.id')
                                                ->get();

        return view('admin.tareas.misasignaciones')->with('tareas', $tareas);
    }

    public function detallesMembers($id)
    {

        $tarea = Tarea::find($id);
        $fecha_i = date_create($tarea->fecha_inicio);
        $tarea->fecha_inicio = date_format($fecha_i, 'd-m-Y');
        $fecha_l = date_create($tarea->fecha_limite);
        $tarea->fecha_limite = date_format($fecha_l, 'd-m-Y');
        $fecha_f = date_create($tarea->fecha_fin);
        $tarea->fecha_fin = date_format($fecha_f, 'd-m-Y');
        return view('empleado.tareas.detalles')->with('tarea', $tarea);

    }

    public function editmembers($id)
    {
        $tarea = Tarea::find($id);
        $fecha_i = date_create($tarea->fecha_inicio);
        $tarea->fecha_inicio = date_format($fecha_i, 'd-m-Y');
        $fecha_l = date_create($tarea->fecha_limite);
        $tarea->fecha_limite = date_format($fecha_l, 'd-m-Y');
        return view('empleado.tareas.edit')->with('tarea', $tarea);
    }

    public function updatemembers(Request $request, $id)
    {
        $tarea = Tarea::find($id);
        // $tarea->nombre_tarea = $request->nombre_tarea;
        // $tarea->prioridad_tarea = $request->prioridad_tarea;
        // $tarea->status_tarea = $request->status_tarea;
        // $tarea->descripcion_tarea = $request->descripcion_tarea;
        // $tarea->fecha_inicio = $request->fecha_inicio;
        // $tarea->fecha_fin = $request->fecha_fin;
        $tarea->fill($request->all());
        $tarea->save();

        Flash::warning("La tarea " .$tarea->nombre_tarea. " ha sido actualizada correctamente.");
        return redirect()->route('admin.tareas.index');
    }

}

resources/views/admin/tareas/asignar.blade.php
@extends('admin.admin_index')

@section('title', 'Asignar Tarea')

@section('title2', 'Seleccione el/los usuarios a los que desea asignar esta tarea')

@section('content')

	<script>

		jQuery(document).ready(function(){
			jQuery(".chosen").chosen();
		});

	</script>
	
	{!! Form::open(['route' => ['admin.tareas.saveasign', $tarea], 'method'=>'POST']) !!}
	{{-- <table class="table table-striped"> --}}

	<div class="form-group">
	<select data-placeholder="Selecciona a los empleados a los cuales deseas asignar esta tarea" class="chosen" multiple="true" name="id_usuario[]" id="id_usuario[]" style="width: 100%;">
		@foreach($usuarios as $usuario)
		<option value='{{$usuario->id}}'>{{$usuario->name}}</option>
		@endforeach
	</select>
	</div> <br>

	

	

{{-- 		<thead>
			<th>Asignar</th>
			<th>Nombre completo</th>
			<th>Categoria</th>
			<th>Numero de nomina</th>
		</thead>
		<tbody>
			@foreach($usuarios as $usuario)
				<tr>
					<td>{!! Form::checkbox('id_usuario[]', $usuario->id) !!}</td>
					<td>{{ $usuario->name }}</td>
					<td>
						
						@if($usuario->type == "administrador")
							<span class="label label-danger">{{ $usuario->type }}</span>
						@else
							<span class="label label-primary">{{ $usuario->type }}</span>
						@endif
					</td>
					<td>{{ $usuario->numero_nomina }}</td>
				</tr>
			@endforeach
		</tbody>
	</table> --}}
	<div class="form-group">
		{!! Form::submit('Asignar tarea', ['class' => 'btn btn-primary btn-sm']) !!}
		<a href="{{ route('admin.tareas.index') }}" class="btn btn-info btn-sm">Volver al listado de tareas</a>
	</div>
	{!! Form::close() !!}
	{!! $usuarios->render() !!}

@endsection

resources/views/admin/tareas/create_tarea.blade.php
@extends('admin.admin_index')

@section('title', 'Crear nueva tarea')

@section('title2', 'Registrar nueva tarea')

@section('content')

		@if(count($errors)>0)
			<div class="alert alert-danger" role="alert">
				<ul>
					@foreach($errors->all() as $error)
						<li> {{ $error }} </li>
					@endforeach
				</ul>
			</div>
		@endif

		
		{!! Form::open(['route'=>'admin.tareas.store', 'method' => 'POST']) !!}
		
		<div class="form-group">
		{!! Form::label('nombre_tarea', 'Nombre Tarea')!!}
		{!! Form::text('nombre_tarea', null, ['class' => 'form-control', 'placeholder' => 'Nombre de la tarea' ,'required']) !!}
		</div>

		<div class="form-group">
		{!! Form::label('prioridad_tarea', 'Prioridad de la tarea')!!}
		{!! Form::select('prioridad_tarea', ['alta' => 'Alta', 'media' => 'Media', 'baja' => 'Baja'], 'baja', ['class' => 'form-control', 'required']) !!}
		</div>

		<div class="form-group">
		{!! Form::label('status_tarea', 'Status de la tarea')!!}
		{!! Form::select('status_tarea', ['pendiente' => 'Pendiente'], 'pendiente', ['class' => 'form-control', 'required']) !!}
		</div>

		<div class="form-group">
		{!! Form::label('descripcion_tarea', 'Descripcion')!!}
		{!! Form::textarea('descripcion_tarea', null, ['class' => 'form-control', 'placeholder' => 'Agrega una descripcion...']) !!}
		</div>

		<div class="form-group">
		{!! Form::label('fecha_inicio', 'Fecha de inicio')!!}
		{!! Form::date('fecha_inicio', \Carbon\Carbon::now()->setLocale('es')) !!}
		</div>

		<div class="form-group">
		{!! Form::label('fecha_limite', 'Fecha limite')!!}
		{!! Form::date('fecha_limite', \Carbon\Carbon::now()->setLocale('es')) !!}
		</div>

		<div class="form-group">
			{!! Form::submit('Crear Tarea', ['class' => 'btn btn-primary btn-sm']) !!}
		

		{!! Form::close() !!}

		<a href="{{ route('admin.tareas.index') }}" class="btn btn-info btn-sm">Volver al listado de tareas</a><br><br>

		</div>

@endsection

resources/views/admin/tareas/detalles.blade.php
@extends('admin.admin_index')

@section('title', 'Detalles Tarea')

@section('title2', 'Tarea '.$tarea->nombre_tarea)

@section('content')

	<div class="panel panel-default">
  		<div class="panel-heading"><span class="glyphicon glyphicon-file"></span>&nbsp;&nbsp;Detalles de la tarea</div>
  			<div class="panel-body">

    			ID: {{ $tarea->id }} <br><br>
    			Nombre: {{$tarea->nombre_tarea}} <br><br>
    			Descripcion: {{ $tarea->descripcion_tarea }} <br><br>
    			Prioridad: {{ $tarea->prioridad_tarea }} <br><br>
    			Status: {{ $tarea->status_tarea }} <br><br>
    			Fecha de inicio: {{ $tarea->fecha_inicio }} <br><br>
    			Fecha limite: {{ $tarea->fecha_limite }} <br><br>
          @if($tarea->fecha_fin == '30-11--0001' )
          <p>Esta tarea aun no ha sido finalizada</p>
          @else
          Fecha finalizacion: {{ $tarea->fecha_fin }} <br><br>
          @endif

			<div style="text-align: right;">
      <a href="{{ route('admin.tareas.index') }}" class="btn btn-primary btn-sm"><span class="glyphicon glyphicon-chevron-left"></span>Volver al listado de tareas</a>
			<a href="{{ route('admin.tareas.edit', $tarea->id) }}" class="btn btn-info btn-sm">Editar Tarea&nbsp;<span class="glyphicon glyphicon-pencil"></span></a>
      <a href="{{ route('admin.tareas.generaPDF', $tarea->id) }}" class="btn btn-warning btn-sm" target="_blank">Imprimir PDF&nbsp;<span class="glyphicon glyphicon-paperclip"></span></a>
      <a href="{{ route('admin.tareas.destroy', $tarea->id) }}" onclick="return confirm('¿Seguro que desea eliminar la tarea seleccionada?, estos cambios no se pueden revertir!.')" class="btn btn-danger btn-sm">Eliminar Tarea&nbsp;<span class="glyphicon glyphicon-remove"></span></a>
			</div>

  			</div>
	</div>

@endsection

resources/views/admin/tareas/edit.blade.php
@extends('admin.admin_index')

@section('title', 'Editar Tarea')

@section('title2', 'Editar la tarea ' .$tarea->nombre_tarea)

@section('content')

		@if(count($errors)>0)
			<div class="alert alert-danger" role="alert">
				<ul>
					@foreach($errors->all() as $error)
						<li> {{ $error }} </li>
					@endforeach
				</ul>
			</div>
		@endif

		
		{!! Form::open(['route'=>['admin.tareas.update', $tarea], 'method' => 'PUT']) !!}
		
		<div class="form-group">
		{!! Form::label('nombre_tarea', 'Nombre Tarea')!!}
		{!! Form::text('nombre_tarea',  $tarea->nombre_tarea, ['class' => 'form-control', 'placeholder' => 'Nombre de la tarea' ,'required']) !!}
		</div>

		<div class="form-group">
		{!! Form::label('prioridad_tarea', 'Prioridad de la tarea')!!}
		{!! Form::select('prioridad_tarea', ['alta' => 'Alta', 'media' => 'Media', 'baja' => 'Baja'], $tarea->prioridad_tarea, ['class' => 'form-control', 'required']) !!}
		</div>

		<div class="form-group">
		{!! Form::label('status_tarea', 'Status de la tarea')!!}
		{!! Form::select('status_tarea', ['finalizada' => 'Finalizada', 'pendiente' => 'Pendiente'], $tarea->status_tarea, ['class' => 'form-control', 'required']) !!}
		</div>

		<div class="form-group">
		{!! Form::label('descripcion_tarea', 'Descripcion')!!}
		{!! Form::textarea('descripcion_tarea', $tarea->descripcion_tarea, ['class' => 'form-control', 'placeholder' => 'Esta es una descripcion']) !!}
		</div>

		<div class="form-group">
		{!! Form::label('fecha_inicio', 'Fecha de inicio')!!}
		{!! Form::date('fecha_inicio',  \Carbon\Carbon::parse($tarea->fecha_inicio)) !!}
		</div>

		<div class="form-group">
		{!! Form::label('fecha_limite', 'Fecha limite')!!}
		{!! Form::date('fecha_limite', \Carbon\Carbon::parse($tarea->fecha_limite)) !!}
		</div>

		<div class="form-group">
		{!! Form::label('fecha_fin', 'Fecha fin')!!}
		{!! Form::date('fecha_fin', \Carbon\Carbon::parse($tarea->fecha_fin)) !!}
		</div>

		<div class="form-group"">
			{!! Form::submit('Actualizar Tarea', ['class' => 'btn btn-primary btn-sm']) !!}
			{!! Form::close() !!}
		<a href="{{ route('admin.tareas.index') }}" class="btn btn-info btn-sm">Volver al listado de tareas</a><br><br>
		</div>

@endsection

resources/views/admin/tareas/index.blade.php
@extends('admin.admin_index')

@section('title', 'Listado de tareas')

@section('title2', 'Tareas')

@section('content')

	<!-- INICIO DEL BUSCADOR -->

		{!! Form::open(['route' => 'admin.tareas.index', 'method' => 'GET', 'class' => 'navbar-form pull-right']) !!}

			<div class="input-group">
				
				{!! Form::text('name', null, ['class' => 'form-control', 'placeholder' => 'Buscar tarea...', 'aria-describedby' => 'search']) !!}

				<span class="input-group-addon" id="search">
					<span class="glyphicon glyphicon-search" aria-hidden="true">
					</span>
				</span>

			</div>

		{!! Form::close() !!}

	<!-- FIN DEL BUSCADOR -->

	<a href="{{ route('admin.tareas.create') }}" class="btn btn-primary btn-sm">Crear nueva tarea&nbsp;<span class="glyphicon glyphicon-plus"></span></a><br><br>
	<table class="table table-striped">
		<thead>
			<th>Nombre tarea</th>
			<th>Prioridad</th>
			<th>Status</th>
			<th>Opciones</th>
		</thead>
		<tbody>
			@foreach($tareas as $tarea)
				<tr>
					<td>{{ $tarea->nombre_tarea }}</td>
					<td>
						
						@if($tarea->prioridad_tarea == "alta")
							<span class="label label-danger">{{ $tarea->prioridad_tarea }}</span>
						@elseif($tarea->prioridad_tarea == "media")
							<span class="label label-warning">{{ $tarea->prioridad_tarea }}</span>
						@else
							<span class="label label-primary">{{ $tarea->prioridad_tarea }}</span>
						@endif
					</td>
					<td>{{ $tarea->status_tarea }}</td>
					<td> 
					<a href="{{ route('admin.tareas.edit', $tarea->id) }}" class="btn btn-warning btn-xs">Editar</a>
					<a href="{{ route('admin.tareas.detalles', $tarea->id) }}" class="btn btn-info btn-xs">Ver detalles</a>
					<a href="{{ route('admin.tareas.asignar', $tarea->id) }}" class="btn btn-primary btn-xs">Asignar</a>
					<a href="{{ route('admin.tareas.destroy', $tarea->id) }}" onclick=" return confirm('¿Seguro que desea eliminar la tarea seleccionada?')" class="btn btn-danger btn-xs">Eliminar</a>
					</td>
				</tr>
			@endforeach
		</tbody>
	</table>
	{!! $tareas->render() !!}


@endsection

resources/views/admin/tareas/misasignaciones.blade.php
@extends('admin.admin_index')

@section('content')
		<?php
		$i = 0;
		?>

		<table class="table table-striped">
					<thead>
						<th>Tarea</th>
						<th>Prioridad</th>
						<th>Status Tarea</th>
						<th>Opciones</th>
					</thead>

		@foreach($tareas as $tarea)
			@if($tarea->id_empleado != Auth::user()->id)
			@else
				<?php
					$i = $i+1;
				?>
				<tbody>
					<tr>
						<td>{{ $tarea->nombre_tarea }}</td>
						<td>{{ $tarea->prioridad_tarea }}</td>
						<td>{{ $tarea->status_tarea }}</td>
						<td> 
						<a href="{{ route('admin.tareas.detalles', $tarea->id) }}" class="btn btn-info btn-xs">Ver detalles</a>
						</td>
					</tr>
			@endif
		@endforeach
		<?php
			
			if ($i == 0) {
				echo "No tienes tareas pendientes.";
			}

		?>
		</tbody>
	</table>
@endsection

resources/views/admin/tareas/pdf.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>PDF</title>
	<link rel="stylesheet" type="text/css" href="../public/css/pdf.css">
  <link rel="stylesheet" href="../public/bootstrap/css/bootstrap.css">
	<img  class="logoshd" src="../public/img/nav_logo.png"/>
	<img  class="logodl" src="../public/img/logodl.png"/> 
  <div id="container">
    <span class="leg_corp">Corporativo DL</span>
  </div>

</head>
<body>
  <br><br>
	<div class="panel panel-default">
  	     <span class="glyphicon glyphicon-euro"></span><div class="panel-heading"><h3>Detalles de la tarea</h3></div>
  			<div class="panel-body">
    			<h4 class="detalles_tarea">Id de la tarea: {{ $tarea->id }} </h4>
    			<h4 class="detalles_tarea">Nombre de la tarea: {{$tarea->nombre_tarea}} </h4>
    			<h4 class="detalles_tarea">Descripcion: {{ $tarea->descripcion_tarea }} </h4>
          <h4 class="detalles_tarea">Prioridad de la tarea: {{ $tarea->prioridad_tarea }}</h4>
          <h4 class="detalles_tarea">Status de la tarea: {{ $tarea->status_tarea }}</h4>
          <h4 class="detalles_tarea">Fecha de inicio: {{ $tarea->fecha_inicio }}</h4>
    		  <h4 class="detalles_tarea">Fecha limite: {{ $tarea->fecha_limite }}</h4>
          <h4 class="detalles_tarea">Fecha finalizacion: {{ $tarea->fecha_fin }} </h4>
        </div>
    </div>

</body>
</html>