app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

//Ruta de inicio

	Route::get('/', ['as' => '/', function () {
    return view('auth.login');
	}]);


//Grupo de rutas para el administrador

	Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'admin']], function(){

		Route::get('/', ['as' => 'inicio', function () {
	    	return redirect()->route('admin.users.index');
		}]);

//Rutas para el modulo de usuarios en el panel del administrador

	Route::resource('users', 'UsersController');

	Route::get('users/{id}/destroy', [

		'uses' => 'UsersController@destroy',
		'as' => 'admin.users.destroy'

	]);

	Route::get('users/{id}/detalles', [

		'uses' => 'UsersController@detalles',
		'as' => 'admin.users.detalles'

	]);

//Rutas para el modulo de tareas en el panel del administrador

	Route::resource('tareas', 'TareasController');

	Route::get('misasignaciones', [

		'uses' 	=> 'TareasController@asignacionesAdmin',
		'as'	=> 'admin.tareas.asignaciones'

		]);

	Route::get('tareas/{id}/destroy', [

		'uses' => 'TareasController@destroy',
		'as' => 'admin.tareas.destroy'

	]);

	Route::get('tareas/{id}/detalles', [

		'uses' => 'TareasController@detalles',
		'as' => 'admin.tareas.detalles'

	]);

	Route::get('tareas/{id}/asignar/',[

		'uses' 	=> 'TareasController@asignar',
		'as' 	=> 'admin.tareas.asignar'

	]);

	Route::get('tareas/{id}/generaPDF',[

		'uses' 	=> 'TareasController@generaPDF',
		'as' 	=> 'admin.tareas.generaPDF'

	]);

	Route::post('tareas/{id}/saveasign',[

		'uses' 	=> 'TareasController@saveasign',
		'as' 	=> 'admin.tareas.saveasign'

	]);

//Rutas para el modulo de reportes en el panel del administrador

	Route::resource('reportes', 'ReportController');

	Route::get('estadisticas',[

			'uses' => 'ReportController@muestaEstadistica',
			'as' => 'admin.reports.stadistics'

		]);

	Route::get('generador',[

		'uses' => 'ReportController@generator',
		'as' => 'admin.reports.generator'

		]);

	Route::post('reportes',[

		'uses' => 'ReportController@generaReport',
		'as' => 'admin.reports.genera'

		]);


//Aqui terminan las rutas el modulo de reportes.

}); //aqui termina el grupo de rutas para el admin

//Aqui comienza el grupo de rutas para los empleados

	Route::group(['prefix' => 'members', 'middleware' => 'auth'], function(){

		Route::get('/', ['as' => 'inicio', function () {
	    	return redirect()->route('members.tareas.index');
		}]);

		Route::resource('tareas', 'MembersController');

			Route::get('tareas/{id}/detalles', [

			'uses' => 'TareasController@detallesMembers',
			'as' => 'members.tareas.detalles'

		]);

		Route::get('tareas/{id}/destroy', [

			'uses' => 'TareasController@destroy',
			'as' => 'members.tareas.destroy'

		]);

		Route::get('tareas/{id}/generaPDF',[

			'uses' 	=> 'TareasController@generaPDF',
			'as' 	=> 'members.tareas.generaPDF'

		]);

		Route::get('tareas/{id}/editmembers',[

			'uses' 	=> 'TareasController@editmembers',
			'as' 	=> 'members.tareas.editmembers'

		]);

		Route::put('tareas/{id}/updatemembers',[

			'uses' 	=> 'TareasController@updatemembers',
			'as' 	=> 'members.tareas.updatemembers'

		]);

	//Rutas para el modulo de reportes en el panel de usuarios

	Route::get('index',[

			'uses' => 'ReportController@reportsIndexMembers',
			'as' => 'members.reports.index'

		]);

	Route::get('estadisticas',[

			'uses' => 'ReportController@muestaEstadistica',
			'as' => 'members.reports.stadistics'

		]);

	Route::get('generador',[

		'uses' => 'ReportController@membersgenerator',
		'as' => 'members.reports.membersgenerator'

		]);

	Route::post('reportes',[

		'uses' => 'ReportController@membersgeneraReport',
		'as' => 'empleado.reports.genera'

		]);

	});


//Rutas para la autenticacion de usuarios (login)

Route::get('auth/login', [

	'uses'	=> 	'Auth\AuthController@getLogin',
	'as'	=>	'auth.login'

	]);

Route::post('auth/login', [

	'uses'	=> 	'Auth\AuthController@postLogin',
	'as'	=>	'auth.login'

	]);

Route::get('admin/auth/logout', [

	'uses'	=> 	'Auth\AuthController@getLogout',
	'as'	=>	'auth.logout'

	]); //aqui terminan las rutas para la autenticacion de usuarios

app/User.php
<?php

namespace App;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

class User extends Model implements AuthenticatableContract,
                                    AuthorizableContract,
                                    CanResetPasswordContract
{
    use Authenticatable, Authorizable, CanResetPassword;

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'users';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'email', 'password', 'type', 'numero_nomina', 'telefono', 'direccion'];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = ['password', 'remember_token'];

    public function empleado_tarea(){

        return $this->belongsTo('App\Empleado_tarea');

    }

    public function admin()
    {
        return $this->type === 'administrador';
    }

    public function empleado()
    {
        return $this->type === 'empleado';
    }

    public function scopeSearchUser($query, $name)
    {
        return $query->where('name', 'LIKE', "%$name%");
    }

}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\User;
use Laracasts\Flash\Flash;
use App\Http\Requests\UsuarioRegistroRequest;

class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $users = User::searchuser($request->name)->orderBy('type', 'DESC')->paginate(5);
        return view('admin.users.index')->with('users', $users);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.users.create_user');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UsuarioRegistroRequest $request)
    {
        $usuario = new User($request->all());
        $usuario->password = bcrypt($request->password);
        $usuario->save();
        
        //enviamos un mensaje con flash de exito antes de redireccionar.
        Flash::success('El usuario ' . $usuario->name . " ha sido registrado exitosamente.");

        //indicamos a que ruta queremos ser redireccionados despues de guardar al usuario
        return redirect()->route('admin.users.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user =  User::find($id);
        return view('admin.users.edit')->with('user', $user);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = User::find($id);
        $user->fill($request->all());
        $user->password = bcrypt($request->password);
        $user->save();

        Flash::warning('El usuario ' .$user->name. ' ha sido actualizado correctamente');  
        return redirect()->route('admin.users.index'); 
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::find($id);
        $user->delete();

        Flash::warning("El usuario " . $user->name . " ha sido eliminado satisfactoriamente.");
        return redirect()->route('admin.users.index');
    }

    public function detalles($id)
    {
        $user = User::find($id);
        return view('admin.users.detalles')->with('user', $user);
    }
}

resources/views/admin/users/create_user.blade.php
@extends('admin.admin_index')

@section('title', 'Registro de usuarios')

@section('title2', 'Registro de usuarios')

@section('content')

		@if(count($errors)>0)
			<div class="alert alert-danger" role="alert">
				<ul>
					@foreach($errors->all() as $error)
						<li> {{ $error }} </li>
					@endforeach
				</ul>
			</div>
		@endif

		
		{!! Form::open(['route'=>'admin.users.store', 'method' => 'POST']) !!}
		
		<div class="form-group">
		{!! Form::label('name', 'Nombre')!!}
		{!! Form::text('name', null, ['class' => 'form-control', 'placeholder' => 'Nombre Completo' ,'required']) !!}
		</div>

		<div class="form-group">
		{!! Form::label('email', 'Email')!!}
		{!! Form::email('email', null, ['class' => 'form-control', 'placeholder' => 'example@gmail.com' ,'required']) !!}
		</div>

		<div class="form-group">
		{!! Form::label('password', 'Contraseña')!!}
		{!! Form::password('password',['class' => 'form-control', 'placeholder' => '***********' ,'required']) !!}
		</div>

		<div class="form-group">
		{!! Form::label('type', 'Tipo de usuario')!!}
		{!! Form::select('type', ['empleado' => 'Empleado', 'administrador' => 'Administrador'], 'empleado', ['class' => 'form-control', 'required']) !!}
		</div>

		<div class="form-group">
		{!! Form::label('numero_nomina', 'Numero de nomina')!!}
		{!! Form::text('numero_nomina', null, ['class' => 'form-control', 'placeholder' => '00000', 'maxlength' => "7" ,'required']) !!}
		</div>

		<div class="form-group">
		{!! Form::label('telefono', 'Telefono')!!}
		{!! Form::text('telefono', null, ['class' => 'form-control', 'placeholder' => 'ex. 5547835471', 'maxlength' => "10" ,'required']) !!}
		</div>

		<div class="form-group">
		{!! Form::label('direccion', 'Direccion')!!}
		{!! Form::text('direccion', null, ['class' => 'form-control', 'placeholder' => 'Av. Plaza Mayor #13','required']) !!}
		</div>

		<div class="form-group">
			{!! Form::submit('Registrar Usuario', ['class' => 'btn btn-primary btn-sm']) !!}
			<a href="{{ route('admin.users.index') }}" class="btn btn-info btn-sm">Volver al listado de usuarios</a>
		</div>

		{!! Form::close() !!}


@endsection

resources/views/admin/users/detalles.blade.php
@extends('admin.admin_index')

@section('title', 'Detalle de usuario')

@section('title2', 'Usuario '. $user->name)

@section('content')

	<div class="panel panel-default">
  		<div class="panel-heading">Detalles del usuario</div>
  			<div class="panel-body">
    			ID del usuario: {{$user->id}} <br><br>
    			Nombre completo: {{$user->name}} <br><br>
    			Correo electronico: {{ $user->email }} <br><br>
    			Tipo de usuario: {{ $user->type }} <br><br>
    			Numero de nomina: {{ $user->numero_nomina }} <br><br>
    			Telefono: {{ $user->telefono }} <br><br>
    			Direccion: {{$user->direccion}} <br><br>

			<div style="text-align: right;">
      <a href="{{ route('admin.users.index') }}" class="btn btn-primary btn-sm"><span class="glyphicon glyphicon-chevron-left"></span>Volver al listado de usuarios</a>
			<a href="{{ route('admin.users.edit', $user->id) }}" class="btn btn-info btn-sm">Editar Usuario&nbsp;<span class="glyphicon glyphicon-pencil"></span></a>
			<a href="{{ route('admin.users.destroy', $user->id) }}" onclick=" return confirm('¿Seguro que desea eliminar el usuario seleccionado?')" class="btn btn-danger btn-sm">Eliminar Usuario&nbsp;<span class="glyphicon glyphicon-remove"></span></a>
			</div>

  			</div>
	</div>

@endsection

resources/views/admin/users/edit.blade.php
@extends('admin.admin_index')

@section('title', 'Editar Usuarios')

@section('title2', 'Editar usuarios')

@section('content')
		
		{!! Form::open(['route'=>['admin.users.update', $user], 'method' => 'PUT']) !!}
		
		<div class="form-group">
		{!! Form::label('name', 'Nombre')!!}
		{!! Form::text('name', $user->name, ['class' => 'form-control', 'placeholder' => 'Nombre Completo' ,'required']) !!}
		</div>

		<div class="form-group">
		{!! Form::label('email', 'Email')!!}
		{!! Form::email('email', $user->email, ['class' => 'form-control', 'placeholder' => 'example@gmail.com' ,'required']) !!}
		</div>

		<div class="form-group">
		{!! Form::label('password', 'Contraseña')!!}
		{!! Form::password('password', ['class' => 'form-control', 'placeholder' => '***********' ,'required']) !!}
		</div>

		<div class="form-group">
		{!! Form::label('type', 'Tipo de usuario')!!}
		{!! Form::select('type', ['empleado' => 'Empleado', 'administrador' => 'Administrador'], $user->type, ['class' => 'form-control', 'required']) !!}
		</div>

		<div class="form-group">
		{!! Form::label('numero_nomina', 'Numero de nomina')!!}
		{!! Form::text('numero_nomina', $user->numero_nomina, ['class' => 'form-control', 'placeholder' => '00000', 'maxlength' => "7" ,'required']) !!}
		</div>

		<div class="form-group">
		{!! Form::label('telefono', 'Telefono')!!}
		{!! Form::text('telefono', $user->telefono, ['class' => 'form-control', 'placeholder' => 'ex. 5547835471', 'maxlength' => "10" ,'required']) !!}
		</div>

		<div class="form-group">
		{!! Form::label('direccion', 'Direccion')!!}
		{!! Form::textarea('direccion', $user->direccion, ['class' => 'form-control', 'placeholder' => 'Av. Plaza Mayor #13','required']) !!}
		</div>

		<div class="form-group">
			{!! Form::submit('Actualizar', ['class' => 'btn btn-primary btn-sm']) !!} 

		{!! Form::close() !!}
		<a href="{{ route('admin.users.index') }}" class="btn btn-info btn-sm">Volver al listado de usuarios</a><br><br>
		</div>

@endsection

resources/views/admin/users/index.blade.php
@extends('admin.admin_index')

@section('title', 'Listado de usuarios')

@section('title2', 'Listado de usuarios')

<!--<script scr="{{ asset('plugins/js/ajaxSearchUser.js') }}"></script>-->



@section('content')

<script>
$(document).on("ready", function() 
{
  	$("#name").keydown
  	( //Evento de presionar una tecla en el campo cuyo id sea "name"
   		function(event)
   			{
    			var param = $("#name").attr("value"); //Se obtiene el valor del campo de texto
    			$("#resultados").load("{{ route('admin.users.index') }}",{name:param}); //Y se envía por vía post al archivo busqueda.php para luego recargar el div con el resultado obtenido
   			}
  	);
});

$(document).on("ready", function() 
{
  $("#name").keyup( //Evento de soltar una tecla en el campo cuyo id sea "name"
   		function(event)
   			{
    			var param = $("#name").attr("value"); //Se obtiene el valor del campo de texto
    			$("#resultados").load("{{ route('admin.users.create') }}",{name:param}); //Y se envía por vía post al archivo busqueda.php para luego recargar el div con el resultado obtenido
   			}
  	);
});
</script>

	<!-- INICIO DEL BUSCADOR -->

		{!! Form::open(['route' => 'admin.users.index', 'method' => 'GET', 'class' => 'navbar-form pull-right', 'id' => 'search_form']) !!}

			<div class="input-group">
				
				{!! Form::text('name', null, ['class' => 'form-control', 'placeholder' => 'Buscar usuario...', 'aria-describedby' => 'search']) !!}

				<span class="input-group-addon" id="search">
					<span class="glyphicon glyphicon-search" aria-hidden="true">
					</span>
				</span>

			</div>

		{!! Form::close() !!}

	<!-- FIN DEL BUSCADOR -->

	<a href="{{ route('admin.users.create') }}" class="btn btn-primary btn-sm">Registrar Nuevo Usuario&nbsp;<span class="glyphicon glyphicon-plus"></span></a><br><br>
	<div id="resultados">
	<table class="table table-striped">
		<thead>
			<th>Nombre completo</th>
			<th>Categoria</th>
			<th>Numero de nomina</th>
			<th>Opciones</th>
		</thead>
		<tbody>
			@foreach($users as $user)
				<tr>
					<td>{{ $user->name }}</td>
					<td>
						
						@if($user->type == "administrador")
							<span class="label label-danger">{{ $user->type }}</span>
						@else
							<span class="label label-primary">{{ $user->type }}</span>
						@endif
					</td>
					<td>{{ $user->numero_nomina }}</td>
					<td> 
					<a href="{{ route('admin.users.edit', $user->id) }}" class="btn btn-warning btn-xs">Editar</a>
					<a href="{{ route('admin.users.detalles', $user->id) }}" class="btn btn-info btn-xs">Ver detalles</a>
					<a href="{{ route('admin.users.destroy', $user->id) }}" onclick=" return confirm('¿Seguro que desea eliminar el usuario seleccionado?')" class="btn btn-danger btn-xs">Eliminar</a>
					</td>
				</tr>
			@endforeach
		</tbody>
	</table>
	</div>
	{!! $users->render() !!}


@endsection